// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elcpbmtumuihaptmpmqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsY3BibXR1bXVpaGFwdG1wbXFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxODE2NzksImV4cCI6MjA2Nzc1NzY3OX0.Y8Q99g0x65E9PFVfWRyDGyq-Or-RRVITSdsG1HvpN94";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});